name: stock_tracker
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  calendar_date_picker2: ^0.2.5
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  connectivity_plus: ^3.0.2
  intl: ^0.17.0

dependency_overrides:
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
